ann/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from tagger import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name = 'index'),
    url(r'^special/', views.show_dashboard, name = 'special'),
    url(r'^tagger/', include(('tagger.urls', 'tagger'), namespace = 'tagger')),
    url(r'^logout/$', views.user_logout, name = 'logout'),
]

iu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name = 'post_list'),
]

tagger/urls.py
from django.urls import path
from django.conf.urls import url
from tagger import views

urlpatterns = [
    url(r'^conv_tagger/$', views.show_conv_tagger, name = 'conv_tagger'),
    url(r'^conv_tagger_wp/$', views.show_conv_tagger_wp, name = 'conv_tagger_wp'),
    url(r'^conv_tagger_inner/$', views.show_conv_tagger_inner, name = 'conv_tagger_inner'),
    url(r'^conv_generator/$', views.show_conv_generator, name = 'conv_generator'),
    url(r'^dashboard/', views.show_dashboard, name = 'dashboard'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^user_login/$', views.user_login, name = 'user_login'),
    url(r'^get_intent/$', views.get_intent, name = 'get_intent'),
    url(r'^get_act/$', views.get_act, name = 'get_act'),
]

tagger/models.py
from django.db import models
from django.conf import settings

from django.contrib.auth.models import User

# Create your models here.

from django.utils import timezone


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    def __str__(self):
        return self.user.username

        
class Conv(models.Model):
    conv_id = models.CharField(max_length = 10)
    turn_id = models.CharField(max_length = 3)
    conv_cat = models.CharField(max_length = 200)
    speaker = models.CharField(max_length = 5)
    text = models.CharField(max_length = 300)
    intent = models.CharField(max_length = 100, null = True)
    ner = models.CharField(max_length = 100, null = True)
    created_date = models.DateTimeField()


class Intent(models.Model):
    intent_id = models.CharField(max_length = 8)
    intent = models.CharField(max_length = 20)

class Act(models.Model):
    act_id = models.CharField(max_length = 8)
    act = models.CharField(max_length = 20)

tagger/forms.py
from django import forms
from tagger.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','password','email')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

tagger/views.py
from django.shortcuts import render
from tagger.forms import UserForm, UserProfileInfoForm
# Create your views here.
from django.utils import timezone
from django.core import serializers

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from django import forms
from .models import UserProfileInfo, Intent, Act, Conv
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt

import json

@login_required
def index(request):
    return render(request, 'tagger/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'tagger/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

@login_required
@csrf_exempt
def show_dashboard(request):
    
    act = ['inform', 'ack', 'introduce', 'notify_success', \
           'request', 'confirm', 'affirm', 'thank', 'bye', 'offer' ]
    intent = ['선물', '리필']
    slot = ['service_type', 'coupon', 'data', 'calling', 'date', 'subscription']
    # Need to turn conv in json format
    return render(request, 'tagger/dashboard.html', \
                  {'act': act, 'slot': slot, 'intent': intent})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        print('login success = {}'.format(user))
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('tagger:dashboard'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'tagger/login.html')

@login_required
def show_conv_tagger(request):
    import json, re
    conv = ''
    if request.method == 'POST':
        conv = request.POST['conv']
        
    elif request.method == 'GET':
        conv = request.GET['conv']
        #cleanr = re.compile('<.*?>')
        #conv = re.sub(cleanr, '', conv)
        # print(conv_json[0]['name'])
        # selected_conv = [x for x in conv_json if x['name'] == post_id][0]
        pass

    act = ['ack', 'affirm', 'bye', 'hello', 'faq_question', 'faq_answer', 'negate', 'thank', 'confirm', 'inform**'
         , 'deny', 'offer', 'reqmore', 'request', 'request_alt', 'select', 'notify_success', 'notify_failure', 'silence'
         , 'introduce']

    intent = ['선물', '리필']
    slot = [
                {'service_type': '(178, 212, 245)'},
                {'intent': '(178, 212, 245)'},
                {'subscription': '(178, 212, 245)'},
                {'price_day': '(178, 212, 245)'},
                {'price_total': '(178, 212, 245)'},
                {'data': '(178, 212, 245)'},
                {'name': '(178, 212, 245)'},
                {'query': '(178, 212, 245)'},
                {'qid': '(178, 212, 245)'},
                {'desc': '(178, 212, 245)'},
                {'message': '(178, 212, 245)'},
                {'calling': '(178, 212, 245)'},
                {'datato': '(178, 212, 245)'},
                {'datefrom': '(178, 212, 245)'},
                {'period': '(178, 212, 245)'},
                {'country': '(178, 212, 245)'},
                {'timebase': '(178, 212, 245)'},
                {'': '(178, 212, 245)'},
                {'timefrom': '(178, 212, 245)'},
                {'timeto': '(178, 212, 245)'},
                {'coupon': '(178, 212, 245)'},
                {'count': '(178, 212, 245)'},
                {'data_add': '(178, 212, 245)'},
                {'month': '(178, 212, 245)'},
                {'card': '(178, 212, 245)'},
                {'card_name': '(178, 212, 245)'},
                {'info': '(178, 212, 245)'},
                {'service_add': '(178, 212, 245)'},
                {'point': '(178, 212, 245)'},
                {'price_use': '(178, 212, 245)'},
                {'term': '(178, 212, 245)'},
    ]
    return render(request, 'tagger/conv_tagger.html', \
                  {'conv': conv, 'act': act, 'slot': slot, 'intent': intent})

@login_required
def show_conv_tagger_inner(request):
    import json, re
    conv = ''
    if request.method == 'POST':
        conv = request.POST['conv']
        
    elif request.method == 'GET':
        conv = request.GET['conv']
        #cleanr = re.compile('<.*?>')
        #conv = re.sub(cleanr, '', conv)
        # print(conv_json[0]['name'])
        # selected_conv = [x for x in conv_json if x['name'] == post_id][0]
        pass

    act = ['ack', 'affirm', 'bye', 'hello', 'faq_question', 'faq_answer', 'negate', 'thank', 'confirm', 'inform**'
         , 'deny', 'offer', 'reqmore', 'request', 'request_alt', 'select', 'notify_success', 'notify_failure', 'silence'
         , 'introduce']

    intent = ['선물', '리필']
    slot = [
                {'service_type': '(178, 212, 245)'},
                {'intent': '(178, 212, 245)'},
                {'subscription': '(178, 212, 245)'},
                {'price_day': '(178, 212, 245)'},
                {'price_total': '(178, 212, 245)'},
                {'data': '(178, 212, 245)'},
                {'name': '(178, 212, 245)'},
                {'query': '(178, 212, 245)'},
                {'qid': '(178, 212, 245)'},
                {'desc': '(178, 212, 245)'},
                {'message': '(178, 212, 245)'},
                {'calling': '(178, 212, 245)'},
                {'datato': '(178, 212, 245)'},
                {'datefrom': '(178, 212, 245)'},
                {'period': '(178, 212, 245)'},
                {'country': '(178, 212, 245)'},
                {'timebase': '(178, 212, 245)'},
                {'': '(178, 212, 245)'},
                {'timefrom': '(178, 212, 245)'},
                {'timeto': '(178, 212, 245)'},
                {'coupon': '(178, 212, 245)'},
                {'count': '(178, 212, 245)'},
                {'data_add': '(178, 212, 245)'},
                {'month': '(178, 212, 245)'},
                {'card': '(178, 212, 245)'},
                {'card_name': '(178, 212, 245)'},
                {'info': '(178, 212, 245)'},
                {'service_add': '(178, 212, 245)'},
                {'point': '(178, 212, 245)'},
                {'price_use': '(178, 212, 245)'},
                {'term': '(178, 212, 245)'},
    ]
    return render(request, 'tagger/conv_tagger_inner.html', \
                  {'user': request.user, 'conv': conv, 'act': act, 'slot': slot, 'intent': intent})

@login_required
def get_intent(request):
    object_list = Intent.objects.all() #or any kind of queryset
    json = serializers.serialize('json', object_list)
    return HttpResponse(json, content_type='application/json')

@login_required
def get_act(request):
    object_list = Act.objects.all() #or any kind of queryset
    json = serializers.serialize('json', object_list)
    return HttpResponse(json, content_type='application/json')
 
@login_required
def show_conv_tagger_wp(request):
    #Need to turn conv in json format
    return render(request, 'tagger/conv_tagger_wp.html')

@login_required
def show_conv_generator(request):
    import json
    if request.method == 'POST':
        post_id = request.POST['post_id']
        
    elif request.method == 'GET':
        # post_id = request.GET.get('post_id')

        # with open('tagger/static/data/conv_1.json', 'r') as f:
        #     conv =  f.read()
        # print('post id = {}'.format(post_id))
        # conv_json = json.loads(conv.replace("'", '')) # json.loads에서는 '과 "이 같이 나오면 순서를 바꿔버림
        
        # print(conv_json[0]['name'])
        # selected_conv = [x for x in conv_json if x['name'] == post_id][0]

        # Temporary
        pass

    act = ['inform', 'ack', 'introduce', 'notify_success', \
           'request', 'confirm', 'affirm', 'thank', 'bye', 'offer' ]
    intent = ['선물', '리필']
    slot = [{'service_type': '(178, 212, 245)'}, {'coupon': '(252, 195, 167)'}, \
            {'data': '(143, 208, 187)'}, {'calling': '(211, 189, 235)'}, \
            {'date': '(154, 159, 249)'}, {'subscription': '(252, 202, 202)'}]
    print(slot)

    #Need to turn conv in json format
    return render(request, 'tagger/conv_generator.html', \
                  {'conv': '', 'act': act, 'slot': slot, 'intent': intent})


def load_excel_to_sqlite(file = '~/Downloads/190112_chat.xlsx'):
    #'~/Downloads/twd_chat.xlsx'
    import pandas as pd

    #import sqlite3
    #conn = create_connection('/Users/kion.kim/work/annot/db.sqlite3')
    #cur = conn.cursor()
    xl  = pd.ExcelFile(file)
    df = xl.parse('sheet1')
    

tagger/templates/tagger/base.html
  {% load static %}
  
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/base/bootstrap.min.css' %}">
  <!-- Custom styles for this template -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/base/simple-sidebar.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/glyphicon.css' %}">

<!DOCTYPE html>
<html lang="en">


<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>DMIG Anonotation Framework</title>

<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/base/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base/bootstrap.bundle.min.js' %}"></script>
<script type="text/javascript" src="../../static/js/base/long-press.js"></script>
<script type="text/javascript" src="../../static/js/base/popper.js"></script>
<script type="text/javascript" src="../../static/js/base/bootstrap.min.js"></script>
{% block script %}
{% endblock %}

</head>

<body>
    
  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
        <div class="sidebar-heading">Annotator</div>
        <div class="list-group list-group-flush">
          <a href="{% url 'tagger:dashboard' %}" class="list-group-item list-group-item-action bg-light">Dashboard</a>
          <a href="{% url 'tagger:conv_tagger_wp' %}" class="list-group-item list-group-item-action bg-light">Conv Tagger</a>
          <a href="{% url 'tagger:conv_generator' %}" class="list-group-item list-group-item-action bg-light">Conv Generator</a>
          <a href="{% url 'admin:index' %}" class="list-group-item list-group-item-action bg-light">Admin</a>
          {% if user.is_authenticated %}
              <a href="{% url 'logout' %}" class="list-group-item list-group-item-action bg-light">Logout</a>
            {% else %}
              <a href="{% url 'tagger:user_login' %}" class="list-group-item list-group-item-action bg-light">Login</a>
            {% endif %}
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

      <div class="container-fluid">
          {% block body_block %}
          {% endblock %}
      </div>
    </div>
    <!-- /#page-content-wrapper -->
  </div>
  <!-- /#wrapper -->
  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

  
</body>

</html>

tagger/templates/tagger/conv_tagger.html
{% extends "tagger/base.html" %}
{% block body_block %}
<link rel="stylesheet" href="../../static/css/base/bootstrap.min.css">
<link rel="stylesheet" href="../../static/css/tagger/tagger.css">
<script type="text/javascript" src="../../static/js/base/jquery.min.js"></script>
<script type="text/javascript" src="../../static/js/tagger/tagger.js"></script>  
<script type="text/javascript" src="../../static/js/base/bootstrap.min.js"></script>
<script type="text/javascript">
    var conv = '{{ conv }}';
    var act = '{{ act }}';
    var intent = '{{ intent }}';
    var slot = '{{ slot }}';
</script>


<!------ Include the above in your HEAD tag ---------->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="chatbody">
                <div class="panel panel-primary">
                    <div class="panel-heading top-bar">
                        <div class="row">
                            <div class="col-md-10">
                                <h3 class="panel-title chat_head"></h3>
                            </div>
                            <div class="col-md-2 col-sm-offset-8">
                                <button type="submit" class="btn btn-warning" id = "submit">저장</button>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body msg_container_base">
                    </div>
                    <div class="panel-footer">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading top-bar">
                    <div class="col-md-8">
                        <h3 class="panel-title"><span class="glyphicon glyphicon-book"></span>  Tagging info</h3>
                    </div>
                </div>
                <div>
                    <div>
                        <div class="jumbotron">
                              <h1>Annotation Guideline or some other contexts!!</h1>
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal" id = 'slot_selector'>
        <!--Creates the popup content-->
        <div class="modal-dialog">
            <div class="modal-content popup-content">
            <!-- Modal Header -->
                <div class="modal-header">
                    <h5 class="modal-title">Slot selector</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
            <!-- Modal body -->
                <div class="modal-body">
                    <form>
                        <div class="row">
                            <div class="col-md-3">
                                <label for='delte'><p>If you want</p> </label>
                            </div>
                            <div class="col-md-7 form-group">
                                <button type="button" class="btn btn-danger" id = "delete_selection" >Delete</button>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-3 form-group">
                                <label for="slot">Slot</label>
                            </div>
                            <div class="col-md-4 form-group" >
                                <select id="slot_selector_in_modal"></select>
                            </div>
                            <div class='col-md-3' id = 'add_slot'>
                                <button type="button" class="btn btn-default btn-sm add_slot"><span class="glyphicon glyphicon-plus"></span></button>
                            </div>
                        </div>
                        <div class='row'>
                            <div class="col-md-3 form-group">
                                <label for="value_in_modal">Value</label>
                            </div>
                            <div class="col-md-7 form-group">
                                <input id='value'></input>
                            </div>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" id = 'intent_selector'>
            <!--Creates the popup content-->
            <div class="modal-dialog">
                <div class="modal-content popup-content">
                <!-- Modal Header -->
                    <div class="modal-header">
                        <h5 class="modal-title">Intent selector</h5>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        
                    </div>
                <!-- Modal body -->
                    <div class="modal-body">
                        <form>
                            <div class="row">
                                <div class="form-group">
                                    <label for="slot">Intent</label>
                                </div>
                                <div class="form-group" >
                                    <select id="intent_selector_in_modal"></select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="slot">Intent</label>
                                </div>
                                <div class="form-group" >
                                    <select id="act_selector_in_modal"></select>
                                </div>
                            </div>
                        </form>
                    </div>
                
                <!-- Modal footer -->
               <!-- <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>      -->
                </div>
            </div>
        </div>

</div>


{% endblock %}

tagger/templates/tagger/dashboard.html
{% extends "tagger/base.html" %}

{% block script %}
<script src="../../static/js/table/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="../../static/js/table/dataTables.bootstrap4.min.js" type="text/javascript"></script>
{% endblock %}

{% block body_block %}
<script>
    var data;
    $(document).ready(function(){
        // Develop mode
        // var conv = getIntitalData();
        // var conv_list = [];
        // for (c in conv){
        //     console.log('conv = ' + c);
        //     conv_list.push({'name': conv[c]['name'], 'sentence': conv[c]['sentences'][1]['text']});
        //     console.log({'name': conv[c]['name'], 'sentence': conv[c]['sentences'][1]['text']});
        // }

        $('#conv_table').DataTable( { 
            "ajax": {
                //'url': 'http://172.23.148.117:9200/twd_index/_search?from=0&size=10',
                'url': '../../static/data/conv.json',
                "cache": true,
                "dataSrc": function(json){
                    console.log(json);
                    let conv_list = [];
                    console.log('count = ' + json['hits']['hits']);
                    data = json['hits']['hits'];
                    for (c in data){
                        conv_list.push({'id': data[c]['_id'], 
                                        'name': data[c]['_source']['name'], 
                                        'sentence': data[c]['_source']['sentences'][0]['text']});
                        console.log({'id': data[c]['_id'], 
                                        'name': data[c]['_source']['name'], 
                                        'sentence': data[c]['_source']['sentences'][0]['text']
                        });
                    }
                    return conv_list;
                }
            },
            "columns": [
                { "data": "id" },
                { "data": "name" },
                { "data": "sentence" },
            ]
        });
        
        $('#intent_table').DataTable( { 
            "ajax": {
                //'url': '../../static/data/intent.json',
                "url": "{% url 'tagger:get_intent' %}",
                "cache": true,
                "dataSrc": function(json){
                    console.log('intent from django = ' + json);
                    let intent_list = [];
                    $.each(json, function(i, a){
                        intent_list.push({'id':a["fields"]["intent_id"], 'name':a["fields"]["intent"]});
                    });
                    return intent_list;
                }
            },
            "columns": [
                { "data": "id" },
                { "data": "name" },
            ]
        });

        $('#act_table').DataTable( { 
            "ajax": {
                'url': "{% url 'tagger:get_act' %}",
                "cache": true,
                "dataSrc": function(json){
                    let act_list = [];
                    $.each(json, function(i, a){
                        act_list.push({'id':a["fields"]["act_id"], 'name':a["fields"]["act"]});
                    });
                    return act_list;
                }
            },
            "columns": [
                { "data": "id" },
                { "data": "name" },
            ]
        });

        $("#conv_table").delegate("tr[role='row']", "click", function(){
            // Get ID for selected conversation
            selected_conv_id = $(this).closest('tr').find('.sorting_1').text();
            selected_conv_with_id = {};
            selected_conv = [];
            $.each(data, function(value){
                if (data[value]['_id'] === selected_conv_id){
                    selected_conv_with_id['id'] = data[value]['_source']['name'];
                    _selected_conv = data[value]['_source']['sentences'];
                    $.each(_selected_conv, function(value){
                        console.log(_selected_conv[value]['speaker']);
                        _selected_conv[value]['text'] = _selected_conv[value]['text'].replace(/\n/g, '').replace(/"/g, '\'');
                        if(_selected_conv[value]['speaker'] !== 'System'){
                            console.log(_selected_conv[value]['created_date'].replace(/:/g,'-'));
                            _selected_conv[value]['created_date'] = _selected_conv[value]['created_date'].replace(/:/g,'-');
                            selected_conv.push(_selected_conv[value]);
                        }
                    });
                }
            });
            selected_conv_with_id['sentences'] = selected_conv;
            console.log('selected conv = ' + JSON.stringify(selected_conv_with_id));

            $.ajax({
                type: 'GET',
                url: "{% url 'tagger:conv_tagger' %}",
                data: {
                    'conv': JSON.stringify(selected_conv),
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function(data){
                    console.log('success');
                    window.location = '/tagger/conv_tagger'+'?conv=' + JSON.stringify(selected_conv_with_id);
                },
            });


        });
    });

    function getIntitalData(){
        var value= $.ajax({ 
            url: '../../static/data/conv_1.json', 
            async: false
        }).responseText;
        return JSON.parse(value);
    }
</script>


<div class='row'>
    <div class="col-md-7">
        <h3>Assigned conversations</h3>
        <table id="conv_table" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>First Sentence</th>
                </tr>
            </thead>
        </table>
    </div>
    
    <div class="col-md-5">
        <div>
            <h3> Intents</h3>
            <table id="intent_table" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Intent ID</th>
                        <th>Intent</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div>
            <h3>Acts</h3>
            <table id="act_table" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Act ID</th>
                        <th>Act</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

{% endblock %}

tagger/templates/tagger/index.html
{% extends "tagger/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to DMIG</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

tagger/templates/tagger/login.html
{% extends 'tagger/base.html' %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
      <form method="post" action="{% url 'tagger:user_login' %}">
        {% csrf_token %}
        {# A more "HTML" way of creating the login form#}
        <label  for="username">Username:</label>
        <input type="text" name="username" placeholder="Username">
        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="Password">
        <input type="submit" name="" value="Login">
      </form>
    </div>
  </div>
{% endblock %}

tagger/templates/tagger/registration.html
{% extends "tagger/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}